name: lint
on: [workflow_call, push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Lint Markdown
        uses: actionshub/markdownlint@main
        with:
          path: "docs"
